#Settings for configuring Energy Conversions
[energy_conversion]
	#How much energy is produced per mB of Hydrogen, also affects Electrolytic Separator usage, Ethene burn rate and Gas-Burning Generator energy capacity.
	# Default: 27
	# Range: 1 ~ 9223372036854775807
	conversionMultiplier = 27

#Custom Replicator Recipe
[replicator_recipes]
	#The recipes added here will be added to the replicator. Write using modid:registeredName#amount, # followed by the amount(not null or zero) of UU matter consumed. For example:[minecraft:stone#10,mekanism:basic_bin#100]
	replicatorRecipe = ["mekanism:basic_bin#100", "mekmm:w#1", "minecraft:stone#50", "minecraft:hopper#10", "mekanism:alloy_atomic#500"]
