#Settings for configuring Large Gas-Burning Generators
[large_gas_generator]
	#The capacity in mB of the chemical tank in the Large Gas-Burning Generator.
	# Default: 486000
	# Range: 1 ~ 9223372036854775807
	tankCapacity = 486000
